sudo: required 
language: generic
services: 
  - docker
before_install: 
  - docker build -t timokito/dockerpro -f Dockerfile.dev . 
script:
  - docker run -e CI=true timokito/Ddockerpro npm run test

  #check 


