sudo: required 
language: generic
services: 
  - docker
before_install: 
  - docker build -t timokito/dockerpro -f Dockerfile.dev . 
script:
  - docker run -e CI=true timokito/dockerpro npm run test
deploy: 
  provider: elasticbeanstalk 
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-384288561359"
  bucket_path: "docker-react"
  on: 
    branch: Feature
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
