sudo: required 
language: generic
services: 
  - docker
before_install: 
  - docker build -t timokito/DockerPRO -f Dockerfile.dev . 
script:
  - docker run -e CI=true timokito/DockerPRO npm run test

  #check 


