language: ruby
rvm:
 - 2.2
 jruby
sudo: required 
services: 
  - docker
before_install: 
  - docker build -t timokito/DockerPRO -f Dockerfile.dev . 
script:
  - docker run -e CI=true timokito/DockerPRO npm run test

  #check 


